version: '3'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=tchadmin
      - MYSQL_ROOT_PASSWORD=secret-pwd
      - MYSQL_PASSWORD=secret-pwd
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db:
    driver: local