version: '3'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=tchadmin
      - MYSQL_ROOT_PASSWORD=secret-pwd
      - MYSQL_PASSWORD=secret-pwd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  db:
    driver: local