version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - MYSQL=$MYSQLDB_CONFIG
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql 

volumes: 
  db: